### PR TITLE
Sphinx documentation framework

### PR DESCRIPTION
**Pull request by itziakos**
This is the sphinx documentation built boilerplate. No context is yet included.

### CODE REVIEW

**Comment by itziakos** [comment]
@roigcarlo, do you have time for a quick review?

**Comment by itziakos** [comment]
@ahashibon the boilerplate documentation is already visible here http://simphony.readthedocs.org/en/latest/

**Comment by roigcarlo** [comment]
@itziakos  At first glance looks good, but let me review it again in a computer just to make sure ( mobile screen now )

**Comment by roigcarlo** [comment]
:+1:

**Comment by itziakos** [comment]
Thanks @roigcarlo

**Pull request merged**
