### PR TITLE
Add docker badge

### PR DESCRIPTION
**Pull request by mehdisadeghi**

### CODE REVIEW

**Comment by stefanoborini** [comment]
The purpose of this image is?

**Comment by mehdisadeghi** [comment]
Pointing to the docker image of this repository.

**Comment by stefanoborini** [comment]
And the purpose of the docker image is?

**Comment by mehdisadeghi** [comment]
Two purposes:
1. Provide a way to easily try the latest simphon-common
2. To be used as base for lammps, liggghts and other docker images

**Pull request merged**
