### PR TITLE
PR: NotImplementedError for get_coordinate on Hexagonal lattices.

### PR DESCRIPTION
**Pull request by tuopuu**
Before proper fixing of the problem, added a NotImplementedError when querying coordinates of a Hexagonal lattice nodes.

### CODE REVIEW

**Comment by tuopuu** [comment]
@roigcarlo, @itziakos, please, take a look.

**Comment by roigcarlo** [comment]
:+1, but I am keeping the issue open, since I understand that this is only temporal

**Comment by itziakos** [comment]
I agree, :+1: , but please do not merge until the 0.1.0 release is done (unless we want to add this fix to the 0.1.0 release)

**Comment by tuopuu** [comment]
Ok, I'll merge when 0.1.0 is done.

**Pull request merged**
