### PR TITLE
V0.2.1 release

### PR DESCRIPTION
**Pull request by nathanfranklin**

### CODE REVIEW

**Comment by nathanfranklin** [comment]
@roigcarlo , @dpinte, @tuopuu , here is a PR making the 0.2.1 release.

**Comment by nathanfranklin** [comment]
@roigcarlo , i fixed the mistake you saw.  is this okay to merge?

**Comment by roigcarlo** [comment]
Yep sure :+1:

**Comment by dpinte** [comment]
:+1:

**Pull request merged**
