### PR TITLE
update docstrings of CUDS items iterators to reflect expected order of items

### PR DESCRIPTION
**Pull request by nathanfranklin**
This addresses #127.

All the the docstrings are updated to clarify the spefic order of items by the CUDS items iterators (e.g. iter_points()).

### CODE REVIEW

**Comment by nathanfranklin** [comment]
Notice that for mesh (ABCMesh ...), I changed the parameter names of the inter methods from "xxx_uids" to "uids".  This is already reflected in the uml diagrams

**Comment by nathanfranklin** [comment]
This PR is ready to review.   @roigcarlo , @itziakos , @tuopuu , @SGGgarcia , if one of you could take a look at it before monday, that would be great.

**Comment by roigcarlo** [comment]
Just a couple of comments:

If we use uid in mesh:
https://github.com/simphony/simphony-common/blob/feature_update_docstring_cuds_items_iters/simphony/cuds/mesh.py#L30
https://github.com/simphony/simphony-common/blob/feature_update_docstring_cuds_items_iters/simphony/cuds/mesh.py#L75

should be ass well "uid"

**Comment by roigcarlo** [comment]
I also have notice that in the mesh class we are always referring the **uid** as **"uid"** in the docstrings,  while in the particles.py for example the **uid** is referred as **"id"**.

I think we should use either of the options but not both at the same time. It looks a little bit confusing while put it all together

**Comment by nathanfranklin** [comment]
@roigcarlo , take a look.  hopefully, they are consistent

**Comment by roigcarlo** [comment]
@nathanfranklin I have uploaded some more, I think it would be easier that way rather than mark them in the code.

Apart from that :+1:

**Comment by nathanfranklin** [comment]
@roigcarlo Perfect!  thanks

**Pull request merged**
