### PR TITLE
Row access data container table

### PR DESCRIPTION
**Pull request by itziakos**
This PR provides an additional pytable table proxy for DataContainers. The IndexDataContinersTable supports the Sequence api and it is optimized for faster read and update operations relative to the normal DataContinerTable which is index using uuid. The limitation is that the delete operations cannot be performed.

@tuopuu, I think should suite better the lattice usecase. 

Please note that there is plenty of space for optimizations but, I would suggest that these take place at a later time and using more realistic usecases.

### CODE REVIEW

**Comment by itziakos** [comment]
@tuopuu, @nathanfranklin  and @roigcarlo, I have updated the PR so that the table description is automatically created by the cuba-generate script

**Comment by itziakos** [comment]
@tuopuu, is this PR ok to merge?

**Comment by tuopuu** [comment]
Yes, it's OK to merge. Current features should be enough to implement FileLattice.

**Comment by itziakos** [comment]
Thanks @tuopuu

**Pull request merged**
