### PR TITLE
Fix warnings when building documentation

### LINKED ISSUE #213: DOC: warnings when building docs
```
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
.....

/home/travis/build/simphony/simphony-common/doc/source/api/cuds.rst:12: WARNING: failed to import abstractmesh.ABCMesh

/home/travis/build/simphony/simphony-common/doc/source/api/cuds.rst:12: WARNING: failed to import abstractparticles.ABCParticles

/home/travis/build/simphony/simphony-common/doc/source/api/cuds.rst:12: WARNING: failed to import abstractlattice.ABCLattice

```

### PR DESCRIPTION
**Pull request by nathanfranklin**
This PR fixes #213 by:
- fixing some ABC module names in documentation
- increases sphinx version to >=1.3 and use the 'classic' theme
- updated some docstrs

### CODE REVIEW

**Comment by nathanfranklin** [comment]
This is stuck for the moment because I currently don't seem to be able to get appveyor to use the right version of Sphinx

**Comment by nathanfranklin** [comment]
This PR is ready for review.

**Comment by nathanfranklin** [comment]
@tuopuu @roigcarlo @mehdisadeghi  can someone review this?

**Comment by mehdisadeghi** [comment]
On Monday 16 November 2015 08:58:40 Nathan Franklin wrote:


@tuopuu[1] @roigcarlo[2] @mehdisadeghi[3] can someone review this? 
—Reply to this email directly or view it on GitHub[4].[5]




I will do it.


Mehdi Sadeghi, M.Sc.Software EngineerFraunhofer IWM 
Freiburgmehdi.sadeghi@iwm.fraunhofer.de

--------
[1] https://github.com/tuopuu
[2] https://github.com/roigcarlo
[3] https://github.com/mehdisadeghi
[4] https://github.com/simphony/simphony-common/pull/214#issuecomment-157096913
[5] https://github.com/notifications/beacon/AC9TdSnhjBtZt21_l7lu0-PJ9D1kDR_Fks5pGgLAgaJpZM4GNF1-.gif

**Comment by roigcarlo** [comment]
Is it not strictly related with this but  raises appears twice in:
https://github.com/simphony/simphony-common/blob/master/simphony/io/h5_cuds.py#L60

Maybe it can be fixed here since is a doc PR

**Comment by nathanfranklin** [comment]
> Is it not strictly related with this but raises appears twice in:
https://github.com/simphony/simphony-common/blob/master/simphony/io/h5_cuds.py#L60
Maybe it can be fixed here since is a doc PR

:+1: I will fix it in a different branch.

**Comment by SGGgarcia** [comment]
Looks ok :+1:

**Comment by mehdisadeghi** [comment]
@nathanfranklin  It looks good to me :+1:

**Pull request merged**
