### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by roigcarlo**
preparation PR for the 0.1.0 Release

### CODE REVIEW

**Comment by itziakos** [comment]
@roigcarlo, can we add a CHANGES.rst file with a list summary of what has changes since 0.0.1

**Comment by itziakos** [comment]
see example https://github.com/enthought/traits-enaml/blob/master/CHANGES.txt

**Comment by roigcarlo** [comment]
Sure, sorry forgot it :S

**Comment by itziakos** [comment]
:+1:

**Pull request merged**
