### PR TITLE
Use coveralls instead of reporting on travis-ci

### PR DESCRIPTION
**Pull request by itziakos**
This PR add the use of coveralls-io to report coverage

### CODE REVIEW

**Comment by itziakos** [comment]
@nathanfranklin  and @ahashibon this PR adds the coveralls service that show detailed coverage reports for the travis-ci builts. It will also sent comments to the PR when the coverage changes due to the code in the PR. In that sense it is easy to spot PRs that degrade the test coverage of the library so we can take action to rectify.

**Comment by itziakos** [comment]
The information is freely available (like the built results of travis-ci for opensource project) at https://coveralls.io/r/simphony/simphony-common

**Comment by itziakos** [comment]
Please note that our current coverage is around 88% which is a valid statement coverage. For more on coverage metric one can read http://www.bullseye.com/coverage.html

**Comment by nathanfranklin** [comment]
Sounds good. :+1:

**Pull request merged**
