### PR TITLE
Add cuba to documentation

### PR DESCRIPTION
**Pull request by nathanfranklin**
This PR addresses #96.

* cuba_generate.py can now generate a rst table with the CUBA information
* this table is used in the documentation

### CODE REVIEW

**Comment by nathanfranklin** [comment]
This PR is ready for review.  

Is there anything else we want to show in the table?  Should we also list the type used in serialization?

**Comment by itziakos** [comment]
> Should we also list the type used in serialization?

I think that io serialization type is separate to the CUBA descriptions. For io I was thinking that a pseudo uml like this https://pytables.github.io/usersguide/introduction.html?highlight=uml#objecttree is probably better.

**Comment by itziakos** [comment]
To clarify, hdf5 serialization layout/format should take place in a separate PR.

**Comment by itziakos** [comment]
the table in looks ok http://simphony.readthedocs.org/en/add-CUBA-to-documentation/cuba_information.html

**Comment by itziakos** [comment]
:+1:

**Comment by nathanfranklin** [comment]
@itziakos  Thanks.  Added one addiotional commit.

**Comment by nathanfranklin** [comment]
> the table in looks ok http://simphony.readthedocs.org/en/add-CUBA-to-documentation/cuba_information.html

yeah, looks ok but very wide. :)      should we open an issue that the whole table can't be seen in the pdf version.

**Comment by itziakos** [comment]
The wire table is probably related to the specific style used http://docs.readthedocs.org/en/latest/theme.html#other-style-notes, We might be able to do something by using a deferent style or having a custom style for SimPhoNy and all simphony packages, but this is not a small task.

**Comment by itziakos** [comment]
:+1:

**Pull request merged**
