### PR TITLE
Problem: MATERIAL_ID is removed but simphony depends on it

### LINKED ISSUE #303: Clean up material_id from simphony-common

### PR DESCRIPTION
**Pull request by mehdisadeghi**
Solution: remove `MATERIAL_ID` and the code that is using that

@stefanoborini @tuopuu @roigcarlo @ahashibon please review this. 

Related issues: #330 #329 

close #303

### CODE REVIEW

**Comment by stefanoborini** [comment]
What do you mean with "simphony depends on it?"

There's a problem with appveyor, and I don't have the powers to restart it, I'll push a neutral commit to restart it.

**Comment by mehdisadeghi** [comment]
> What do you mean with "simphony depends on it?"

I mean it is used in some modules and the tests fail if we remove it.

**Comment by stefanoborini** [comment]
Do you remember which ones specifically?

**Comment by mehdisadeghi** [comment]
> Do you remember which ones specifically?

simphony/io/tests/test_data_container_table.py, simphony/io/tests/test_h5_cuds.py, simphony/io/tests/test_h5_lattice.py, simphony/io/tests/test_indexed_data_container_table.py

**Comment by mehdisadeghi** [comment]
@stefanoborini have you reviewed this?

**Comment by stefanoborini** [comment]
@mehdisadeghi JYULB uses it. What are we supposed to replace it with? Material has no storage for this quantity.

**Comment by ahashibon** [comment]
Material Id should be moved to wrapper, no need for it anymore.

Sent from my iPhone

On 11 Jan 2017, at 20:01, Stefano Borini <notifications@github.com<mailto:notifications@github.com>> wrote:


@mehdisadeghi<https://github.com/mehdisadeghi> JYULB uses it. What are we supposed to replace it with? Material has no storage for this quantity.

**Comment by kemattil** [comment]
@ahashibon is correct: in the new design the "Material ID" is used only internally by the JYULB wrappers.

**Comment by stefanoborini** [comment]
@ahashibon @kemattil I can't move it to wrapper. The DataContainer accepts only CUBA keys, and apparently the code needs to extract a LatticeNode which contains information about the material_id. LatticeNode only accepts DataContainer "restricted" data, so I have no way of returning this information unless I remove the restriction on datacontainer altogether, or rework LatticeNode to accept an extra_data parameter, with all the potential consequences of an extended API.

**Comment by ahashibon** [comment]
the information on the node should contain the MATERIAL object it self (or some kind of ref to it). I am afraid we need a bit more time to finalize the specs (will send a review this week with Mehdi). There should be a change in the wrapper side at the same  time we change common before the release is possible.

Sent from my iPhone

On 12 Jan 2017, at 12:22, Stefano Borini <notifications@github.com<mailto:notifications@github.com>> wrote:


@ahashibon<https://github.com/ahashibon> @kemattil<https://github.com/kemattil> I can't move it to wrapper. The DataContainer accepts only CUBA keys, and apparently the code needs to extract a LatticeNode which contains information about the material_id. LatticeNode only accepts DataContainer "restricted" data, so I have no way of returning this information unless I remove the restriction on datacontainer altogether, or rework LatticeNode to accept an extra_data parameter, with all the potential consequences of an extended API.

**Comment by stefanoborini** [comment]
@ahashibon  Ok, I leave jyuld for later and move on to something else.

**Pull request merged**
