### PR TITLE
Problem: `data` property should be a reference

### PR DESCRIPTION
**Pull request by mehdisadeghi**
Solution: revert corresponding change made in #335 

@ahashibon @stefanoborini I reverted a changed which was my bad.

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
@stefanoborini @ahashibon The regenerate solves also the `FACE` change (which is removed from cuba.yml)

**Comment by ahashibon** [comment]
Thanks @mehdisadeghi, looks good to me.

**Comment by stefanoborini** [comment]
Ok, now I am confused. Didn't we agree that we had to return a copy?

**Comment by stefanoborini** [comment]
Ok, this PR is doing unrelated things so I will do the following:

1. update against a new version of simphony-metadata, extracting the relevant bits.
2. if green, merge it back here.
3. merge the yapf patch I have already.

**Comment by mehdisadeghi** [comment]
@stefanoborini This PR is desired since it provides the expected behavior. 

BTW, I realized even simphony v3.0 has been inconsistent regarding `data` property. Some classes such as `Particle` treat it as reference and some others like `Particles` treat it as copy.

**Pull request merged**
