### PR TITLE
Fix datacontainer particles, mesh and lattice datasets

### PR DESCRIPTION
**Pull request by ahashibon**
DS.data should return the data container, and not a copy. This is consistent with dataset elements and metadata generated classes (cuds_item). 
@mehdisadeghi please review.

### CODE REVIEW

**Comment by stefanoborini** [comment]
Good for me, provided that the client code is aware of this change

**Comment by ahashibon** [comment]
@stefanoborini can we merge this?

**Comment by stefanoborini** [comment]
@ahashibon I just verified that the same change needs to be done in the generated classes. This first requires a change in the generator, then a rebuild of the meta classes in this PR.

**Comment by stefanoborini** [comment]
@ahashibon correction, it's already there. Merging.

**Pull request merged**
