### PR TITLE
PR: FileLattice enhancements

### PR DESCRIPTION
**Pull request by tuopuu**
This PR aims to fix issue #108.

* Renamed FileLattice related files to H5Lattice. 
* H5Lattice now uses only a reference to the group where it stores lattices. 
* H5Lattice constructor is now split into two parts, create_new which creates new lattices in H5CUDS
file, and __init__ which returns references to lattices existing in files.

### CODE REVIEW

**Comment by itziakos** [comment]
:+1:

**Comment by itziakos** [comment]
@tuopuu this PR also implements the Lattice part of #88

**Comment by itziakos** [comment]
@roigcarlo, This PR implements part of #88 (milestone 0.1.1) and part of #109. For consistency I would suggest that we add #109 to the 0.1.1 milestone and add related comments to clarify what will be included

**Comment by tuopuu** [comment]
@itziakos, yes that's right. I couldn't find the correct number for that issue when submitting this PR.

**Comment by tuopuu** [comment]
Merged #109

**Comment by roigcarlo** [comment]
Added this PR to Milestone 0.1.1

**Pull request merged**
