### PR TITLE
Cleanup try except blocks

### PR DESCRIPTION
**Pull request by itziakos**

### CODE REVIEW

**Comment by itziakos** [comment]
@roigcarlo  or @nathanfranklin, is this ok to merge? (note that the coveralls failure marginal, probably due to rounding errors)

**Comment by nathanfranklin** [comment]
:+1:

**Comment by roigcarlo** [comment]
https://github.com/simphony/simphony-common/blob/small-cleanup-on-try-except-logic/simphony/io/h5_cuds.py#L58

As you have deleted the other comments it looks strange to left this here. Apart from that ok.

**Comment by itziakos** [comment]
Thanks @roigcarlo, I will merge when travis-ci passes

**Pull request merged**
