### PR TITLE
Discover load plugin modules

### PR DESCRIPTION
**Pull request by itziakos**
This allows discovery and load of extension modules that have been registered to the `simphony.visualization` and `simphony.engine` entry points. (see provided example plugin).

**pending**:
- [x] tests

### CODE REVIEW

**Comment by itziakos** [comment]
hmm... I think we can make some testing code for the entry_points

**Comment by itziakos** [comment]
This PR is ready for review

**Comment by itziakos** [comment]
@roigcarlo, @nathanfranklin and @tuopuu, Please feel welcome to review.

**Comment by nathanfranklin** [comment]
Looks good.  I went through the steps of making lammps-md a engine plug-in to see I understood everything.

**Pull request merged**
