### PR TITLE
Updated README and setup.py

### PR DESCRIPTION
**Pull request by roigcarlo**
This PR updated the author of setup.py and adds the url of the project as is requested in https://github.com/simphony/simphony-common/issues/73

### CODE REVIEW

**Comment by nathanfranklin** [comment]
Looks good.  Can you update the author in conf.py as well (https://github.com/simphony/simphony-common/blob/master/doc/source/conf.py#L234)

**Comment by roigcarlo** [comment]
Sure, Should I update 

https://github.com/simphony/simphony-common/blob/master/doc/source/conf.py#L82
https://github.com/simphony/simphony-common/blob/master/doc/source/conf.py#L264
https://github.com/simphony/simphony-common/blob/master/doc/source/conf.py#L278
https://github.com/simphony/simphony-common/blob/master/doc/source/conf.py#L299-301

as well?

**Comment by nathanfranklin** [comment]
Yes, I think so.

**Comment by nathanfranklin** [comment]
:+1:

**Pull request merged**
