### PR TITLE
Problem: rearranging modules is impossible due to absolute imports

### PR DESCRIPTION
**Pull request by mehdisadeghi**
Solution: use relative imports with dot notation

P.S: this is a refactoring PR, nothing new.

### CODE REVIEW

**Comment by stefanoborini** [comment]
You probably mean the opposite. You are making them relative.

**Comment by mehdisadeghi** [comment]
> You probably mean the opposite. You are making them relative.

Hehe, yeah just corrected it! :)

**Comment by stefanoborini** [comment]
Sorry!

**Comment by mehdisadeghi** [comment]
@stefanoborini Your response time is really short! Thumbs up :+1:

**Comment by stefanoborini** [comment]
Still unclear. Do you want them relative or absolute?

**Comment by mehdisadeghi** [comment]
> Still unclear. Do you want them relative or absolute?

@stefanoborini I want them to be relative to the current package using the dot notation in order to be able to rearrange packages and modules in the project folder.

**Pull request merged**
